// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-guDZjU75w43WXb06qRioQBx5fHCd5c',
    appId: '1:766379202701:web:dac74e9113d1ea7fd96ac4',
    messagingSenderId: '766379202701',
    projectId: 'list-fb5d7',
    authDomain: 'list-fb5d7.firebaseapp.com',
    databaseURL:
        'https://list-fb5d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'list-fb5d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz0sC2enMiigsX-qzldD1AZ0Pt6NdCX7Y',
    appId: '1:766379202701:android:d8c5b3740e2fc065d96ac4',
    messagingSenderId: '766379202701',
    projectId: 'list-fb5d7',
    databaseURL:
        'https://list-fb5d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'list-fb5d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkMC3wmXJY6OR0YYH5TXslamMsHgwicVI',
    appId: '1:766379202701:ios:09c4903a6e2fdba8d96ac4',
    messagingSenderId: '766379202701',
    projectId: 'list-fb5d7',
    databaseURL:
        'https://list-fb5d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'list-fb5d7.firebasestorage.app',
    iosBundleId: 'com.example.listApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkMC3wmXJY6OR0YYH5TXslamMsHgwicVI',
    appId: '1:766379202701:ios:09c4903a6e2fdba8d96ac4',
    messagingSenderId: '766379202701',
    projectId: 'list-fb5d7',
    databaseURL:
        'https://list-fb5d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'list-fb5d7.firebasestorage.app',
    iosBundleId: 'com.example.listApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2-guDZjU75w43WXb06qRioQBx5fHCd5c',
    appId: '1:766379202701:web:5a4782c743a7e55ad96ac4',
    messagingSenderId: '766379202701',
    projectId: 'list-fb5d7',
    authDomain: 'list-fb5d7.firebaseapp.com',
    databaseURL:
        'https://list-fb5d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'list-fb5d7.firebasestorage.app',
  );
}
